/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MarketplacePost: typeof import('./src/components/MarketplacePost.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StrengthGauge: typeof import('./src/components/StrengthGauge.vue')['default']
    TeamSearch: typeof import('./src/components/TeamSearch.vue')['default']
  }
}
